services:
  - type: web
    name: webtienganh-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn webtienganh.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: webtienganh.settings
      - key: PYTHON_VERSION
        value: 3.10

